### PR TITLE
Some minor changes

### LINKED ISSUE #9: analysis UI bug: last trick assigned to wrong side
in the https://lorserker.github.io/ben/demo/viz.html?deal=1 playback if you click next card through out the hand the last trick is scored as going to the defense N/S instead of to the E/W that won it.

seems to be related to the fact that the trick count is not updated after all four cards have been played (it's only updated when the next trick starts)

### LINKED ISSUE #34: in the appserver pass pass pass pass results in the same hand being shown as the first time this happned
Bug in the appserver for pass pass pass pass.   If you go home and then click the None button you don't get to the hand you just passed out you always get to the same one.

So basically the review on hands that are passed out is broken.

### PR DESCRIPTION
**Pull request by ThorvaldAagaard**
1: Fixed #9 
2: Added p_make_contract in the display of replay of a board
3: Added som space before the delete link as I have deleted some boards by accident
4: Changes in viz.html - #43 
5: Fixed #34 
6: Increased columns for pprint, so a board is printed on one line
7: Added a comment of how to serve a specific deal from the gameserver
8: Added restart.py, that starts the gameserver, so it is possible to terminate and restart it - this is only tested on windows.

### CODE REVIEW

**Comment by lorserker** [comment]
@ThorvaldAagaard nice! thank you :+1: 

i don't understand the purpose of `restart.py`
we could just run `python gameserver.py` to start it and kill the process to stop it, no?

**Comment by ThorvaldAagaard** [comment]
Yes, but that is killing my anaconda window, so I have to start a command prompt and switch to the /src-directory.

Using restart.py i can just use Ctrl-C that will teminate the output from the server (but not the server), so restart will now kill the process and start the gameserver again.

But no need to include it, I have just found it very helpful

**Comment by drk1806** [comment]
I have a question regarding BEN. Is it possible to play a pbn file with this? In other words, start the program and pass a pbn file to play.

**Comment by ThorvaldAagaard** [comment]
Yes and No. You will have to take the input from the PBN-file and paste it into gameserver.py

These three lines in the PBN-file is to be used
```
[Vulnerable "None"]
[Deal "N:QT.J742.K96.J864 K9632.KT83.T3.T9 A.Q9.AQ8754.A532 J8754.A65.J2.KQ7"]
[Declarer "S"]
```
So add this in gameserver.py

    rdeal = ('QT.J742.K96.J864 K9632.KT83.T3.T9 A.Q9.AQ8754.A532 J8754.A65.J2.KQ7, 'S None')

And start the gameserver, at it will deal this board

**Comment by drk1806** [comment]
Thanks , just to make sure, this will be the syntax
python gameserver.py rdeal = ('QT.J742.K96.J864 K9632.KT83.T3.T9 A.Q9.AQ8754.A532 J8754.A65.J2.KQ7', 'S None')

**Comment by ThorvaldAagaard** [comment]
No you will have to change it in the file gameserver.py 

image

**Comment by drk1806** [comment]
Thanks again, and I can have multiple deals like the example shown above right? Usually they have about 15 deals in a session.

**Comment by ThorvaldAagaard** [comment]
No, then you will have to add some logic to select the next deal. Perhaps I will find time to add that feature to the gameserver.

How are you going to use it?

**Comment by drk1806** [comment]
Just play a session from Spingold or Vanderbilt on my imac.

Jay

**Comment by lorserker** [comment]
@ThorvaldAagaard let's exclude the restart.py from the PR and then we are ready to merge

**Comment by lorserker** [comment]
@drk1806 @ThorvaldAagaard some thoughts about feeding deals from a pbn file:

there is this [function](https://github.com/lorserker/ben/blob/main/src/game.py#L432)  which is a generator of random deals

```python
deal_source  = ranndom_deal_source()
deal1 = next(deal_source)
deal2 = next(deal_source)
....
```

we could create another generator function, say `pbn_deal_source` and replace only the `deal_source` in the code.

we could implement an

**Comment by ThorvaldAagaard** [comment]
@lorserker I think I have deleted restart.py from the pull request, so please check if it is ok now.

**Comment by ThorvaldAagaard** [comment]
@drk1806 
> Just play a session from Spingold or Vanderbilt on my imac. Jay

Will you add a PBN-file, you would like to play, and I will see if I can create a simple way for you to do it.

I assume, that you just want the board and bid and play it against 2 BENs, and with BEN as partner

**Comment by drk1806** [comment]
Here is a sample pbn file I would like to play with ben.

Thanks
Jay

**Comment by ThorvaldAagaard** [comment]
@drk1806 
> Here is a sample pbn file I would like to play with ben. Thanks Jay

Seems the file was eaten by either your mailsystem or github, try attaching it from the github website

**Comment by drk1806** [comment]
[o4_nr.zip](https://github.com/lorserker/ben/files/11958497/o4_nr.zip)
Here is the file that got truncated through mail client.

**Comment by ThorvaldAagaard** [comment]
I have created a new gameserver, that will read the boards from a file in BEN-format, and just cycle thru the boards.

To create the file in BEN-format I have written a smal program, that converts a PBN-file. 

This solution can be improved a lot, but seems to be working for now

This should be the first board from your file
image

I will make a pull-request and Lorand will then hopefully include it in the repository.

For now you can do the following

Save this as pbn2ben.py
```
import datetime

import deck52

from collections import deque
from typing import NamedTuple


class Deal(NamedTuple):
    dealer: str
    vulnerable: str
    hands: str

def load(fin):
    dealer, vulnerable = None, None
    for line in fin:
        if line.startswith('[Dealer'):
            dealer = extract_value(line)
        elif line.startswith('[Vulnerable'):
            vuln_str = extract_value(line)
            vulnerable = {'NS': 'N-S', 'EW': 'E-W', 'All': 'Both'}.get(vuln_str, vuln_str)
        elif line.startswith('[Deal'):
            hands_pbn = extract_value(line)
            [seat, hands] = hands_pbn.split(':')
            hands_nesw = [''] * 4
            first_i = 'NESW'.index(seat)
            for hand_i, hand in enumerate(hands.split()):
                hands_nesw[(first_i + hand_i) % 4] = hand
            print("'" + ' '.join(hands_nesw) + "','" + dealer + " " + vulnerable + "' ")
        else:
            continue

def extract_value(s: str) -> str:
    return s[s.index('"') + 1 : s.rindex('"')]


if __name__ == '__main__':

    try:
        with open("o4_nr.pbn", "r") as file:
            lines = file.readlines()
        load(lines)

    except Exception as ex:
        print('Error:', ex)
        raise ex
```

save this as gameserverfromfile.py
```
import sys
import uuid
import shelve
import asyncio
import websockets
import functools

import game
import human

from nn.models import Models
from websockets.exceptions import ConnectionClosedError

MODELS = Models.load('../models')

print('models loaded')


def worker(driver):
    print('worker', driver)
    asyncio.new_event_loop().run_until_complete(driver.run())
board_no = []
boards = [...] 

async def handler(websocket, path, board_no):
    print(f'got websocket connection {websocket}')

    rdeal = tuple(boards[board_no[0]].replace("'","").rstrip('\n').split(','))

    print(f"Board: {board_no[0]+1}" )
    print(rdeal)

    driver = game.Driver(MODELS, human.WebsocketFactory(websocket))
    driver.set_deal(*rdeal)
    driver.human = [False, False, True, False]

    try:
        await driver.run()

        with shelve.open('gamedb') as db:
            deal_bots = driver.to_dict()
            db[uuid.uuid4().hex] = deal_bots
            print('saved')
            board_no[0] = board_no[0] + 1
            if (board_no[0] > len(boards)):
                board_no[0] = 0
    
    except ConnectionClosedError  as ex:
        print('User left')
        

    except Exception as ex:
        print('Error:', ex)
        raise ex

with open("input.ben", "r") as file:
    board_no.append(0) 
    boards = file.readlines()

start_server = websockets.serve(functools.partial(handler, board_no=board_no), "0.0.0.0", 4443)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()


```

first execute pbn2.ben.py with the command

```
python pbn2ben.py > input.ben
```

then start the server with the command
```
python gameserverfromfile.py
```

Try this and let me know how it goes.

**Comment by drk1806** [comment]
Thanks so much.

I guess the pbn file o4_nr needs to be in the same directory where I am
running the python command?

Jay

**Comment by drk1806** [comment]
I followed your instructions (put the o4_nr.pbn in src directory too)
I got this error in gameserverfromfile.py
models loaded
got websocket connection <websockets.legacy.server.WebSocketServerProtocol
object at 0x000001B31B2359C8>
Board: 1
('ÿþ\x00A\x008\x003\x00.\x00K\x00Q\x009\x002\x00.\x00J\x00T\x007\x005\x004\x00.\x005\x00
\x00K\x009\x005\x002\x00.\x00A\x00J\x00T\x00.\x00Q\x009\x00.\x008\x006\x003\x002\x00
\x00J\x007\x006\x00.\x006\x005\x004\x00.\x006\x003\x002\x00.\x00A\x00K\x009\x004\x00
\x00Q\x00T\x004\x00.\x008\x007\x003\x00.\x00A\x00K\x008\x00.\x00Q\x00J\x00T\x007\x00\x00',
'\x00\x00S\x00 \x00N\x00-\x00S\x00\x00 \x00')
confirmer <human.ConfirmSocket object at 0x000001B31B24ED48>
connection handler failed

**Comment by drk1806** [comment]
Ok, so after the first board plays, how do I go to next board?

Jay

**Comment by ThorvaldAagaard** [comment]
This is the first page
image

And I click on "Play Now", then I play the board, and when finished, there is a small link "Home" at the left bottom, that i click on. That brings me back to the first page, and I can review the board just played, or I can click on "Play Now" that will take the next board.

Lorand has implemented that, and probably because it was not intended to play a session like you are doing. But as I said, there is place for improvements

**Comment by drk1806** [comment]
Yep, that works. Thanks again.

**Comment by lorserker** [comment]
merging the PR.

@ThorvaldAagaard thanks for your contribution!

if you like, you can open another PR for the play-from-file stuff.
maybe we could add an optional command line argument when starting the gameserver so we don't have the gameserver twice.

**Comment by ThorvaldAagaard** [comment]
> if you like, you can open another PR for the play-from-file stuff. maybe we could add an optional command line argument when starting the gameserver so we don't have the gameserver twice.

yes, And I think the parsing of the PBN to the internal format of BEN also can be included in the gameserver. I was jsut focused on getting something to work

**Comment by drk1806** [comment]
I am having this error trying to play a new file. It is erroring out, could this be a problem with input file.
[o4_nrprb.zip](https://github.com/lorserker/ben/files/11968887/o4_nrprb.zip)

**Comment by drk1806** [comment]
got websocket connection <websockets.legacy.server.WebSocketServerProtocol object at 0x00000136D5486B08>
Board: 1
('ÿþ\x002\x00.\x009\x005\x004\x003\x002\x00.\x00J\x005\x003\x00.\x00Q\x007\x005\x002\x00 \x00A\x00Q\x00T\x007\x00.\x00K\x00T\x008\x00.\x00A\x00K\x00Q\x00T\x00.\x00J\x004\x00 \x00J\x009\x008\x006\x003\x00.\x00Q\x006\x00.\x008\x006\x004\x002\x00.\x00A\x006\x00 \x00K\x005\x004\x00.\x00A\x00J\x007\x00.\x009\x007\x00.\x00K\x00T\x009\x008\x003\x00\x00', '\x00\x00N\x00 \x00N\x00o\x00n\x00e\x00\x00 \x00')
confirmer <human.ConfirmSocket object at 0x00000136D5498F48>
connection handler failed
Traceback (most recent call last):
  File "C:\Users\jay\miniconda3\envs\ben\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "C:\Users\jay\miniconda3\envs\ben\lib\site-packages\websockets\legacy\server.py", line 1189, in _ws_handler
    )(websocket, websocket.path)
  File "gameserverfromfile.py", line 34, in handler
    driver.set_deal(*rdeal)
  File "C:\Users\jay\miniconda3\envs\ben-main\src\game.py", line 61, in set_deal
    self.deal_data = DealData.from_deal_auction_string(self.deal_str, auction_str, 32)
  File "C:\Users\jay\miniconda3\envs\ben-main\src\bidding\binary.py", line 30, in from_deal_auction_string
    dealer_ix = dealer[auction_parts[0]]
KeyError: '\x00\x00N\x00'

**Comment by drk1806** [comment]
[input.zip](https://github.com/lorserker/ben/files/11969514/input.zip)
Here is the input.ben file.

**Comment by drk1806** [comment]
Perfect. That worked like a charm.
As always, thank you for being so responsive.
I am now playing these deals and comparing them with other softwares like Jack, Q plus etc.

**Comment by ThorvaldAagaard** [comment]
Good luck.
Next time you find a problem, please create a new issue, as this in fact is a pull-request that is completed.

**Comment by ThorvaldAagaard** [comment]
@drk1806 Lorand have merged my chabges into this repository, so the gameserver can now be started with a PBN-file as input. It would be nice if you try that.

**Comment by drk1806** [comment]
Thanks I will try, so what would be the command to start gameserver with
pbn file in the new build.

Jay

**Comment by ThorvaldAagaard** [comment]
After activating conda
```python gameserver.py --boards filename```
It can use the ben-format, and also the PBN-format

**Comment by drk1806** [comment]
Thanks, I'll check it out.

On another topic, at the NABC tournament, I met the "owner" of Ben who told
me Ben was going to be transitioned to some other program.

Do you know anything about that?

Jay

**Comment by ThorvaldAagaard** [comment]
Sounds strange  but I hope Lorand will comment on that. 

Could it be IntoBridge, that is using Ben at the moment, but at the same time is developing a new robot? Lorand has open sourced BEN, so I think the term developer is better than owner.

**Comment by drk1806** [comment]
So trying this with command,
python gameserver.py --boards f2_nr.pbn

and getting this error,

**Comment by lorserker** [comment]
Regarding ownership questions.

I encourage anyone to use ben in their product. I'm also happy if they develop it further.
Best is to share the learnings and improvements to make ben better for everyone, but I'm not stressing with such requirements. Everyone should contribute at the level they are comfortable with.
With IntoBridge I don't have any business relationship. I am glad that they use ben and this way hundreds of people can enjoy playing with it.
How IntoBridge uses robots and which robots they use is completely up to them. Of course I hope that they will continue to use ben :)

**Comment by ThorvaldAagaard** [comment]
@drk1806 Open a new issue with the problem with the gameserver and show the error

**Comment by drk1806** [comment]
Lorand

Irrespective of this being a commercial product or not, is there an effort
to build on Ben as a separate program? I heard about it at NABC in Chicago.

Jay

**Comment by drk1806** [comment]
Issue opened.
https://github.com/lorserker/ben/issues/54

**Comment by ThorvaldAagaard** [comment]
I am testing a build for a separate program, but we need to improve the GUI first :-)

Tensorflow is not that happy to be included in a program, but I expect I will get it to work.

**Comment by drk1806** [comment]
What will be the new program called?

**Comment by ThorvaldAagaard** [comment]
Not yet

**Comment by drk1806** [comment]
Ok , let me know if you want to test the new version/GUI out.

Thank
Jay

**Pull request merged**
