### PR TITLE
#74, support ghcr.io using github actions

### PR DESCRIPTION
**Pull request by larrycai**
* add container package in github
* github action is used, which is triggered by tag
* tag version is vx.x.x, support pre-release

### CODE REVIEW

**Comment by larrycai** [comment]
after merge, give a tag "v0.2.0-alpha" to verify. github action is triggered by tag

it shall automatically generate package `ghcr.io/lorserker/ben:0.2.0-alpha`, not `latest`

**Comment by larrycai** [comment]
Not sure whether Line 33 needs extra permission or setup or not.  It is automatically done in my forked repo

> password: ${{ secrets.GITHUB_TOKEN }}

**Comment by ThorvaldAagaard** [comment]
I have merged your changes, and tagged the current version as v0.2.0-alpha

What should I now check?

**Comment by larrycai** [comment]
https://github.com/lorserker/ben/pkgs/container/ben 

Cool it is there!! it exists automatically, since it is not official release, so `latest` tag is not applied

>ghcr.io/lorserker/ben:0.2.0-alpha

If we released v0.2.0, then it will appear

````
ghcr.io/lorserker/ben:0.2.0
ghcr.io/lorserker/ben:latest # kind of soft link to 0.2.0
````

The pipeline is https://github.com/lorserker/ben/actions/runs/6796484547

**Comment by larrycai** [comment]
@lorserker  super cool ;-), now we can prepare for a new official release to close #52

**Pull request merged**
